
# ==================================================
# KONFIGURASI JUPYTER BOOK
# PROYEK SAINS DATA - UTM
# ==================================================

title: Analisis Kualitas Udara Labang
author: Achmad Saiful Fuadi
logo: logo.jpg

# Pengaturan eksekusi notebook
execute:
  execute_notebooks: off

# Pengaturan tampilan website
html:
  use_issues_button: true
  use_repository_button: true
  use_fullscreen_button: true
  home_page_in_navbar: true
  extra_navbar: |
    <p>Proyek Sains Data - UTM</p>
  css:
    - custom.css

# Informasi repository GitHub
repository:
  url: https://github.com/username-anda/nama-repo
  path_to_book: materi
  branch: main

# Pastikan file peta HTML dan citra ikut build
sphinx:
  config:
    html_extra_path:
      - uts_assets
